### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by PineappleGOD1**

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
Was this intentional? Not to mention the options you changed in the config will break the plugin...

**Comment by PineappleGOD1** [comment]
i dont know what i was doin

**Comment by PineappleGOD1** [comment]
so shhhh

**Comment by PineappleGOD1** [comment]
i was just testing

**Comment by Thatsmusic99** [comment]
I appreciate the honesty, been there before

**Pull request closed without merging**
