### PR TITLE
Fix potential NPE when no other players online

### PR DESCRIPTION
**Pull request by HaHaWTH**
This PR added another null check to form response, in order to prevent null pointers when there's no other players online:)

logs: https://mclo.gs/To8KmiC

### CODE REVIEW

**Review by Thatsmusic99 — COMMENTED** [review]
Checking the stacktrace, this check wouldn't prevent this error unfortunately :( the first line indicates that it happens within the response object (which is consequently not null). 

Cumulus has updated since then but isn't present in the latest versions of Geyser/Floodgate, so I'm not sure who this would be an issue for - but at least I now know Cumulus has an update I would need to prepare for

**Comment by HaHaWTH** [comment]
Oh I see, thanks for ur explanation. :/
So now need to wait for floodgate to update right?

**Comment by Thatsmusic99** [comment]
Likely so, Floodgate is currently on 1.1.2 of Cumulus, but the latest is 2.0.0-SNAPSHOT (presumably in the works): https://github.com/GeyserMC/Floodgate/blob/49bd56446fa10931b1c4abf6609055571a4ae105/build-logic/src/main/kotlin/Versions.kt#L28

However, in the response implementation, the null variable is not meant to be: https://github.com/GeyserMC/Cumulus/blob/496d5572221037aff6682838d2678795dd0f0a22/src/main/java/org/geysermc/cumulus/response/impl/CustomFormResponseImpl.java#L261

I wonder if there's a way to tell if someone picked a certain option or none at all - an alternative could also be the command (/tpa and /tpahere) telling the player that no one else is online. Is that something you want to give a try?

**Comment by HaHaWTH** [comment]
Ah yes, I would like to do that( Check if there are other players online before sending a form.
Also can prevent this error)

**Pull request closed without merging**
