### PR TITLE
Add pom.xml

### PR DESCRIPTION
**Pull request by animeavi**

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
Will have to discuss this with Nie a bit since whilst the last AT repo used Maven but I don't think he wanted to use Maven in this repo.

**Comment by animeavi** [comment]
This just makes it easy to build without IDEA or any other IDE but not strictly necessary.

**Comment by Thatsmusic99** [comment]
Gotcha on that. We’ll assess this pull request whilst we can. If Nie isn’t happy with it, you can use Maven on your end just fine, I have no problem with that, and if other contributors in the future request it we’ll consider it again.

**Comment by Thatsmusic99** [comment]
Closing now; Nie recently decided to go back to using Maven and re-added it all himself.

**Pull request closed without merging**
