### PR TITLE
Update floodgate dependency

### PR DESCRIPTION
**Pull request by Jens-Co**

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
Is there any breaking API that you're aware that comes with this?

I'm not gonna pull an Enjin and reject this PR over something this small (considering I wasn't aware of an update until now, so thank you for bumping this), and are you aware of any implications it could have for #58 (which is related)?

I would check myself but unfortunately I'm not quite right in the head today and just need some time off.

**Comment by Thatsmusic99** [comment]
Seems to not affect compilation and has no impact on #58. Will merge over now.

**Comment by Jens-Co** [comment]
Forgot to respond on your question. We did a huge refractor on Geyser itself, floodgate should not be affected by it but there where some changes within floodgate to.

**Comment by Thatsmusic99** [comment]
Appreciate the response, no worries. I'll continue digging to see where I get with the existing issue.

**Comment by Jens-Co** [comment]
If you need any help on Geyser/Floodgate integration feel free to join our Discord server. https://discord.gg/geysermc

We had someone in Discord that was telling us about this plugin and it having some issues but I totally forgot what it was. :p

**Pull request merged**
