### PR TITLE
Fix /back command behavior

### PR DESCRIPTION
**Pull request by animeavi**
Previously it would set the location *after* the TP, which is kinda useless.

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
Had no notifications on any of these pull requests in the past, I figured Nie hadn't set up the Discord webhook to keep track of pull requests (which is how I'd usually know if a pull request is opened).

Why would it be any different if the location was set after teleporting? It's not just meant to keep track of AT's teleport commands, but also all teleports. Or at least from what I know it's probably only just a tick after, which is like 0.05 seconds.

**Comment by animeavi** [comment]
Well from my testing it's setting the loc **after**.

**Comment by Thatsmusic99** [comment]
Yes but I don’t really see the problem with it, if anything the problem of it being before is that you don’t know if the teleportation was cancelled by another plugin, and setting that back location too early becomes problematic. I am going to make adjustments so that it indefinitely avoids that, and plus this won’t work with a new commit I’ll push later since it also logs death location when a player dies.

**Comment by animeavi** [comment]
Alright I like this behavior and use it in my server but I think I misunderstood intended the purpose of the command. I'll close this.

**Comment by Thatsmusic99** [comment]
Right. Thank you for your contribution regardless, it is appreciated - any more pull requests you want to make don't be afraid to! I just need to check this page more often now or get Nie to enable the pull request notifications on Discord...

**Pull request closed without merging**
