### PR TITLE
Allow to use selectors in /rtp / /tpr

### PR DESCRIPTION
**Pull request by Geolykt**
This would allow to use these commands in command blocks for example

### CODE REVIEW

**Review by Thatsmusic99 — CHANGES_REQUESTED** [review]
Quite honestly having played with selectors before, I wasn't expecting this to work, but [holy crap, this is brilliant!](https://gyazo.com/6b7d36cd23387291c9586611f0e7995e)

Only thing I would suggest with this in mind is placing this behind a permission so someone with the standard `at.admin.tpr.other` permission - assuming it's meant to only teleport a single person - doesn't go around throwing `/tpr world @a` like it's free candy. You're free to argue against this, just my two cents.

**Comment by Thatsmusic99** [comment]
This did make me realise as well that a forced purchase is made on players (as presented in the video) if economy features are enabled, whether or not I intended this, I can look into getting around that in the future, hence I do think it'd be best to have this put behind a permission.

**Comment by Geolykt** [comment]
Yep, will do that

**Comment by Geolykt** [comment]
Don't know the specifics about how permission handling is done in this plugin, but this should work from my experience

**Review by Thatsmusic99 — APPROVED** [review]
Perfect! Will look into getting merged sometime in the future, got a lot of focus on upcoming exams.

**Comment by Thatsmusic99** [comment]
I've pushed some changes here by accident, ignore that. 

I'll get this into the dev builds.

**Pull request merged**
