### PR TITLE
Fix #35

### LINKED ISSUE #35: [BUG] Help HomesCommand not working
### Description
If you use `/athelp HomesCommand` nothing happens. Every other help command works

### Reproducing
1. Use `/athelp HomesCommand` ingame
2. Nothing happens - not even an error gets thrown

### Expected Behaviour
A list of the commands regarding home teleportation

### Server
 - Server Type: Paper
 - Server Version: 1.16.5
 - Build: 586

### Plugin Information
- Plugin version: 5.4.7

### PR DESCRIPTION
**Pull request by LucasMucGH**
Closed #35

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
I do want to make my own addition to this, but am in a virtual work experience webinar right now so won't be able to until later. If you want to get ahead of me, I want to add an "or" check to AtHelp (line 82) to check if the user uses "HomesCommand" instead because whilst the typo has been patched in the plugin itself, it won't apply itself to existing config files. (Of course, I do want to address the general command layout in AT in a future update) - cheers in advance!

**Comment by LucasMucGH** [comment]
Yeah, that's a great idea. I didn't even think of it.
I hope my code is in line with your coding style.

Just wanted to mention, that you are doing a great job with this plugin, and it is by far the best one out there for tpa, warps and homes.

**Comment by Thatsmusic99** [comment]
It absolutely is, don't worry. That class in itself is a bit messy regardless, hence why I want to redo it in the future. :) I'll test this PR once I've finished with the fixes for #34. 

Thank you very much for your kind words as well, I haven't heard them a lot very often but they always put a smile on my face! Thank you as well for reporting the issues you found with the plugin in such great detail which may have not been immediately obvious either, I always appreciate it.

**Comment by Thatsmusic99** [comment]
Confirmed to fix the issue at hand - thank you for contributing to Advanced Teleport!

**Pull request merged**
