### PR TITLE
Fix a memory leak caused when importing/exporting data

### PR DESCRIPTION
**Pull request by Thatsmusic99**

### CODE REVIEW

**Comment by Geolykt** [comment]
If I looked at it right this is more of a hide than a real fix

**Comment by Thatsmusic99** [comment]
The main issue this caused here was that the async scheduler was called too often using ATPlayer#getPlayer(String), this pretty much bars that from a specific use case. It doesn't cover importing yet and I want to cover that soon. The crash report looked like this: https://mclo.gs/pZJs34M

Are there any other cases where it would be considered a cover-up rather than a fix? And what with the previous location?

**Comment by Geolykt** [comment]
That must have been massive amounts of data then

**Comment by Thatsmusic99** [comment]
yup it was lmao

The server no longer crashes but still investigating issues surrounding the import/export function, some of which are pending pushes.

**Comment by Geolykt** [comment]
My mention about the previous location can be discarded for newer spigot versions due to <https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/664000a476523c44baab2d95a1044659e7f957d9#src/main/java/org/bukkit/Location.java>

**Comment by Thatsmusic99** [comment]
2019 isn't all too bad considering I want to chuck older version support out of the window.

And it's fine! I appreciate it being brought up to my attention at most, I'll keep it in mind if it develops into a problem.

**Pull request merged**
